### PR TITLE
Add locks around writeReadController

### LINKED ISSUE #18: Binary polling broke profile moves
It appears that binary polling broke profile moves.

Profile moves work using this commit:  8e9cd590e3ecb557b76fb228347e92fc8dc2412a

Profile moves hang using this commit:  e9615c7a59f0683761b57c112780f47c925e7229

### PR DESCRIPTION
**Pull request by kmpeters**
to prevent conficts between the poller thread and the profile move thread.  Fixes #18

### CODE REVIEW

**Comment by MarkRivers** [comment]
I don't think you should need locks around writeReadController.  The problem is that writeReadBinary is not being done as an atomic operation:
```
	// Send the query command
	memcpy(outString_, output, outBytes);
	status = pasynOctetSyncIO->write(pasynUserController_, outString_, outBytes, SPIIPLUS_CMD_TIMEOUT, &nwrite);
	
	// The reply from the controller has a 4-byte header and a 1-byte suffix
	status = pasynOctetSyncIO->read(pasynUserController_, packetBuffer, inBytes, SPIIPLUS_ARRAY_TIMEOUT, &nread, &eomReason);

```
It is being done as a write() followed by a read() which is not atomic.  They could be replaced with writeRead().  However, there is also a flush done above this.  These all need to be done with the asynPortDriver lock held so no other threads can talk to the controller while writeReadBinary is executing.

**Comment by kmpeters** [comment]
``writeReadBinary`` clears the terminators:

https://github.com/epics-motor/motorAcsMotion/blob/187f6095f70ed0b459980c690dc70f88ed10d8c7/acsMotionApp/src/SPiiPlusDriver.cpp#L499-L501

and restores them at the end:

https://github.com/epics-motor/motorAcsMotion/blob/187f6095f70ed0b459980c690dc70f88ed10d8c7/acsMotionApp/src/SPiiPlusDriver.cpp#L555-L557

The locks are needed while the terminator is cleared otherwise non-binary commands sent from other threads fail.

**Comment by kmpeters** [comment]
I used gdb to see what was going on when the IOC hung:

https://github.com/epics-motor/motorAcsMotion/issues/18#issuecomment-956467744

**Comment by kmpeters** [comment]
Without the locks around ``writeReadController``, a call to ``writeReadInt`` from the profile thread while the poller is executing ``writeReadBinary`` would to the following:

Call ``writeReadController``:

https://github.com/epics-motor/motorAcsMotion/blame/49bf25fa40590d2b68f113d9d2de93c724d16793/acsMotionApp/src/SPiiPlusDriver.cpp#L357

which calls ``pasynOctetSyncIO->writeRead``:

https://github.com/epics-modules/motor/blob/master/motorApp/MotorSrc/asynMotorController.cpp#L790

which is where the locking is actually done:

https://github.com/epics-modules/asyn/blob/master/asyn/interfaces/asynOctetSyncIO.c#L246-L271

If the asyn terminator changes while the exection is here, does the terminator change have an effect?

https://github.com/epics-modules/asyn/blob/ee3d45a6cbddf13e3ac82d04f65b8467c9f6ec35/asyn/interfaces/asynOctetSyncIO.c#L246

**Comment by MarkRivers** [comment]
> The locks are needed while the terminators are cleared otherwise non-binary commands sent from other threads fail.

I realize that.  But what I am saying is that I think it would be sufficient to call lock around all of the code in writeReadBinary.  All other threads should only be running with the lock already held, so they can't call writeReadController anyway?

**Comment by kmpeters** [comment]
My debugging showed the the locks around writeReadBinary **didn't** prevent writeReadController from being called.

**Pull request merged**
